import type {
  ActionMetadata,
  AllowedAsset,
  Creator,
  Discoverable,
  FilterTag,
  Journey,
  LocalizedText,
  MediaAsset,
  MvpSeedContent,
  Opportunity,
  Person,
  Place,
  Project,
  SourceMetadata,
  TravelStyle,
} from "../types";

const localized = (en: string, ru: string): LocalizedText => ({ en, ru });

const media = (
  src: AllowedAsset,
  en: string,
  ru: string,
): MediaAsset => ({
  src,
  alt: localized(en, ru),
});

const editorialSource = (en: string, ru: string): SourceMetadata => ({
  type: "veya-editorial",
  label: localized("Veya editorial", "Редакция Veya"),
  note: localized(en, ru),
});

const conceptSource = (en: string, ru: string): SourceMetadata => ({
  type: "veya-concept",
  label: localized("Veya concept", "Концепт Veya"),
  note: localized(en, ru),
});

const partnerCallSource = (en: string, ru: string): SourceMetadata => ({
  type: "partner-call",
  label: localized("Veya partner call", "Поиск партнеров Veya"),
  note: localized(en, ru),
});

const demoSource = (): SourceMetadata => ({
  type: "demo",
  label: localized("Demo profile", "Демо-профиль"),
  note: localized(
    "Fictional profile created for interface testing. This is not a real traveler.",
    "Вымышленный профиль для тестирования интерфейса. Это не реальный путешественник.",
  ),
});

const detailAction = (
  href: string,
  en = "View details",
  ru = "Подробнее",
): ActionMetadata => ({
  type: "view-details",
  label: localized(en, ru),
  href,
  external: false,
});

const interestAction = (slug: string): ActionMetadata => ({
  type: "express-interest",
  label: localized("Join the concept interest list", "Добавиться в лист интереса"),
  href: `/interest?item=${slug}`,
  external: false,
});

const partnerAction = (slug: string): ActionMetadata => ({
  type: "partner-call",
  label: localized("Discuss a possible partnership", "Обсудить возможное партнерство"),
  href: `/interest?item=${slug}`,
  external: false,
});

export const filterTags = [
  { slug: "albania", label: localized("Albania", "Албания"), group: "geography" },
  { slug: "balkans", label: localized("Balkans", "Балканы"), group: "geography" },
  {
    slug: "mediterranean",
    label: localized("Mediterranean", "Средиземноморье"),
    group: "geography",
  },
  {
    slug: "montenegro",
    label: localized("Montenegro", "Черногория"),
    group: "geography",
  },
  {
    slug: "north-macedonia",
    label: localized("North Macedonia", "Северная Македония"),
    group: "geography",
  },
  { slug: "coast", label: localized("Coast", "Побережье"), group: "theme" },
  { slug: "mountains", label: localized("Mountains", "Горы"), group: "theme" },
  { slug: "nature", label: localized("Nature", "Природа"), group: "theme" },
  { slug: "culture", label: localized("Culture", "Культура"), group: "theme" },
  { slug: "community", label: localized("Community", "Сообщество"), group: "theme" },
  { slug: "wellbeing", label: localized("Wellbeing", "Благополучие"), group: "theme" },
  {
    slug: "remote-work",
    label: localized("Remote work", "Удаленная работа"),
    group: "theme",
  },
  { slug: "local-food", label: localized("Local food", "Местная еда"), group: "theme" },
  { slug: "adventure", label: localized("Adventure", "Приключения"), group: "theme" },
  { slug: "learning", label: localized("Learning", "Обучение"), group: "theme" },
  {
    slug: "volunteering",
    label: localized("Volunteering", "Волонтерство"),
    group: "theme",
  },
  {
    slug: "hitchhiking",
    label: localized("Hitchhiking", "Автостоп"),
    group: "theme",
  },
  { slug: "slow-pace", label: localized("Slow pace", "Медленный темп"), group: "format" },
  {
    slug: "small-group",
    label: localized("Small group", "Малая группа"),
    group: "format",
  },
  { slug: "long-stay", label: localized("Long stay", "Долгое проживание"), group: "format" },
  { slug: "walking", label: localized("Walking", "Прогулки"), group: "format" },
  { slug: "low-budget", label: localized("Low budget", "Низкий бюджет"), group: "format" },
  {
    slug: "partner-call",
    label: localized("Partner call", "Поиск партнера"),
    group: "content-state",
  },
  {
    slug: "editorial",
    label: localized("Editorial selection", "Редакционная подборка"),
    group: "content-state",
  },
  {
    slug: "concept",
    label: localized("Concept", "Концепт"),
    group: "content-state",
  },
  {
    slug: "demo-profile",
    label: localized("Demo profile", "Демо-профиль"),
    group: "content-state",
  },
] as const satisfies readonly FilterTag[];

export const travelStyles = [
  {
    slug: "slow-travel",
    title: localized("Slow travel", "Медленные путешествия"),
    summary: localized(
      "Stay long enough to understand the rhythm of a place.",
      "Оставаться достаточно долго, чтобы почувствовать ритм места.",
    ),
    description: localized(
      "Slow travel favors fewer stops, local routines and time for unplanned discoveries.",
      "Медленное путешествие выбирает меньше остановок, местный ритм и время для незапланированных открытий.",
    ),
    practicalNote: localized(
      "Plan flexible days and avoid changing accommodation too often.",
      "Оставляйте дни гибкими и не меняйте жилье слишком часто.",
    ),
    media: media(
      "/assets/veya-world.png",
      "Illustrated Veya road through a travel world",
      "Иллюстрированная дорога Veya через мир путешествий",
    ),
    tagSlugs: ["slow-pace", "culture", "community"],
    relatedSlugs: ["gjirokaster-stone-city", "himara-coast", "roads-villages-shared-tables"],
    source: editorialSource(
      "Veya educational content for the first tester release.",
      "Образовательный материал Veya для первой тестовой версии.",
    ),
    action: detailAction("/travel-styles/slow-travel", "Explore slow travel", "Изучить медленные путешествия"),
  },
  {
    slug: "nature-travel",
    title: localized("Nature travel", "Путешествия в природу"),
    summary: localized(
      "Build a journey around landscapes, trails and time outdoors.",
      "Строить путешествие вокруг ландшафтов, троп и времени на воздухе.",
    ),
    description: localized(
      "Nature travel can range from gentle coastal walks to demanding mountain routes.",
      "Путешествия в природу могут включать и спокойные прогулки у моря, и сложные горные маршруты.",
    ),
    practicalNote: localized(
      "Check weather, access, equipment and local guidance before setting out.",
      "Перед выходом проверяйте погоду, доступность маршрута, снаряжение и местные рекомендации.",
    ),
    media: media(
      "/assets/albania-coast-road.jpg",
      "Road between Albanian coast and mountain landscapes",
      "Дорога между албанским побережьем и горными ландшафтами",
    ),
    tagSlugs: ["nature", "mountains", "coast"],
    relatedSlugs: ["theth-albanian-alps", "himara-coast", "theth-trail-companion-interest"],
    source: editorialSource(
      "Veya educational content for the first tester release.",
      "Образовательный материал Veya для первой тестовой версии.",
    ),
    action: detailAction("/travel-styles/nature-travel", "Explore nature travel", "Изучить путешествия в природу"),
  },
  {
    slug: "cultural-travel",
    title: localized("Cultural travel", "Культурные путешествия"),
    summary: localized(
      "Discover a place through its stories, streets, crafts and daily life.",
      "Открывать место через его истории, улицы, ремесла и повседневную жизнь.",
    ),
    description: localized(
      "Cultural travel rewards curiosity, respectful questions and attention to local context.",
      "Культурные путешествия раскрываются через любопытство, уважительные вопросы и внимание к местному контексту.",
    ),
    practicalNote: localized(
      "Learn basic local etiquette and leave time for museums, markets and conversations.",
      "Изучите основы местного этикета и оставьте время для музеев, рынков и разговоров.",
    ),
    media: media(
      "/assets/community-hero.jpg",
      "Travelers sharing stories in a local setting",
      "Путешественники делятся историями в местной обстановке",
    ),
    tagSlugs: ["culture", "learning", "walking"],
    relatedSlugs: ["gjirokaster-stone-city", "berat-riverside-quarters", "albania-story-walk-concept"],
    source: editorialSource(
      "Veya educational content for the first tester release.",
      "Образовательный материал Veya для первой тестовой версии.",
    ),
    action: detailAction("/travel-styles/cultural-travel", "Explore cultural travel", "Изучить культурные путешествия"),
  },
  {
    slug: "community-travel",
    title: localized("Community travel", "Путешествия через сообщества"),
    summary: localized(
      "Meet a place through people who live and create there.",
      "Знакомиться с местом через людей, которые там живут и создают.",
    ),
    description: localized(
      "Community travel centers shared activities, local initiatives and clear mutual expectations.",
      "Путешествия через сообщества строятся вокруг общих занятий, местных инициатив и ясных взаимных ожиданий.",
    ),
    practicalNote: localized(
      "Understand what a community offers, what it asks from visitors and how consent is handled.",
      "Уточняйте, что предлагает сообщество, чего оно ждет от гостей и как устроено согласие участников.",
    ),
    media: media(
      "/assets/community-hero.jpg",
      "Small group gathering outdoors",
      "Встреча небольшой группы на природе",
    ),
    tagSlugs: ["community", "small-group", "learning"],
    relatedSlugs: ["balkans-community-atlas", "berat-local-table-host-call", "demo-traveler-ana"],
    source: editorialSource(
      "Veya educational content for the first tester release.",
      "Образовательный материал Veya для первой тестовой версии.",
    ),
    action: detailAction("/travel-styles/community-travel", "Explore community travel", "Изучить путешествия через сообщества"),
  },
  {
    slug: "volunteering-travel",
    title: localized("Volunteering travel", "Волонтерские путешествия"),
    summary: localized(
      "Combine travel with a defined contribution to a local initiative.",
      "Совмещать путешествие с понятным вкладом в местную инициативу.",
    ),
    description: localized(
      "Responsible volunteering starts with real needs, transparent roles and respect for local expertise.",
      "Ответственное волонтерство начинается с реальных потребностей, прозрачных ролей и уважения к местной экспертизе.",
    ),
    practicalNote: localized(
      "Verify the organiser, duties, costs, safeguarding and expected time commitment.",
      "Проверяйте организатора, обязанности, расходы, правила безопасности и ожидаемую продолжительность участия.",
    ),
    media: media(
      "/assets/community-hero.jpg",
      "People collaborating in a shared outdoor space",
      "Люди сотрудничают в общем пространстве на природе",
    ),
    tagSlugs: ["volunteering", "community", "learning"],
    relatedSlugs: ["balkans-community-atlas", "albania-local-creator-call", "demo-traveler-maksim"],
    source: editorialSource(
      "Veya educational content only. No volunteer placement is offered by this seed entry.",
      "Только образовательный материал Veya. Эта запись не предлагает волонтерское место.",
    ),
    action: detailAction("/travel-styles/volunteering-travel", "Explore volunteering travel", "Изучить волонтерские путешествия"),
  },
  {
    slug: "remote-work-travel",
    title: localized("Remote work travel", "Путешествия с удаленной работой"),
    summary: localized(
      "Combine focused work with a temporary base in a new place.",
      "Совмещать сосредоточенную работу с временной базой в новом месте.",
    ),
    description: localized(
      "A good work stay balances reliable essentials, local life and boundaries between work and exploration.",
      "Хорошее проживание для работы сочетает надежные базовые условия, местную жизнь и границы между работой и исследованием.",
    ),
    practicalNote: localized(
      "Confirm internet, workspace, time zone, transport and total living costs before committing.",
      "До подтверждения проверяйте интернет, рабочее место, часовой пояс, транспорт и общую стоимость жизни.",
    ),
    media: media(
      "/assets/veya-world.png",
      "Illustrated Veya world with routes and places",
      "Иллюстрированный мир Veya с маршрутами и местами",
    ),
    tagSlugs: ["remote-work", "long-stay", "slow-pace"],
    relatedSlugs: ["home-for-living-and-working", "mediterranean-work-stay-interest", "demo-traveler-luka"],
    source: editorialSource(
      "Veya educational content for the first tester release.",
      "Образовательный материал Veya для первой тестовой версии.",
    ),
    action: detailAction("/travel-styles/remote-work-travel", "Explore remote work travel", "Изучить путешествия с удаленной работой"),
  },
  {
    slug: "low-budget-travel",
    title: localized("Low budget travel", "Бюджетные путешествия"),
    summary: localized(
      "Use time, flexibility and local knowledge to travel with fewer expenses.",
      "Использовать время, гибкость и местные знания, чтобы путешествовать с меньшими расходами.",
    ),
    description: localized(
      "Low budget travel is a planning style, not a promise that every route is cheap or risk free.",
      "Бюджетное путешествие является стилем планирования, а не обещанием, что любой маршрут будет дешевым или безрисковым.",
    ),
    practicalNote: localized(
      "Keep an emergency reserve and verify transport, border and accommodation conditions.",
      "Сохраняйте резерв на непредвиденные случаи и проверяйте транспорт, границы и условия проживания.",
    ),
    media: media(
      "/assets/albania-coast-road.jpg",
      "Open road through an Albanian landscape",
      "Открытая дорога через албанский ландшафт",
    ),
    tagSlugs: ["low-budget", "adventure", "slow-pace"],
    relatedSlugs: ["theth-albanian-alps", "theth-trail-companion-interest", "demo-traveler-maksim"],
    source: editorialSource(
      "Veya educational content for the first tester release.",
      "Образовательный материал Veya для первой тестовой версии.",
    ),
    action: detailAction("/travel-styles/low-budget-travel", "Explore low budget travel", "Изучить бюджетные путешествия"),
  },
  {
    slug: "wellbeing-travel",
    title: localized("Wellbeing travel", "Путешествия для благополучия"),
    summary: localized(
      "Choose a calmer rhythm centered on rest, movement, nature and good routines.",
      "Выбирать спокойный ритм с отдыхом, движением, природой и полезными привычками.",
    ),
    description: localized(
      "Wellbeing travel supports everyday balance without making medical claims or replacing professional care.",
      "Путешествия для благополучия поддерживают повседневный баланс без медицинских обещаний и без замены профессиональной помощи.",
    ),
    practicalNote: localized(
      "Check accessibility, food, activity level and qualified support for any specific health need.",
      "Проверяйте доступность, питание, уровень нагрузки и квалифицированную поддержку при особых потребностях здоровья.",
    ),
    media: media(
      "/assets/community-hero.jpg",
      "Quiet shared moment in a natural setting",
      "Спокойный общий момент в природной обстановке",
    ),
    tagSlugs: ["wellbeing", "nature", "slow-pace"],
    relatedSlugs: ["week-of-healthy-rhythm", "lake-ohrid-shore", "balkans-wellbeing-place-call"],
    source: editorialSource(
      "Veya educational content. It is not medical advice or a treatment offer.",
      "Образовательный материал Veya. Это не медицинская рекомендация и не предложение лечения.",
    ),
    action: detailAction("/travel-styles/wellbeing-travel", "Explore wellbeing travel", "Изучить путешествия для благополучия"),
  },
  {
    slug: "hitchhiking-travel",
    title: localized("Hitchhiking", "Автостоп"),
    summary: localized(
      "Explore flexible overland travel with strong attention to context and safety.",
      "Исследовать гибкие наземные маршруты с особым вниманием к контексту и безопасности.",
    ),
    description: localized(
      "Hitchhiking conditions differ by country, road, season and traveler experience.",
      "Условия автостопа различаются в зависимости от страны, дороги, сезона и опыта путешественника.",
    ),
    practicalNote: localized(
      "Research local rules, choose safe stopping points, share plans and keep transport alternatives.",
      "Изучайте местные правила, выбирайте безопасные точки, сообщайте планы близким и сохраняйте запасные варианты транспорта.",
    ),
    media: media(
      "/assets/albania-coast-road.jpg",
      "Road crossing coastal and mountain terrain",
      "Дорога через прибрежный и горный рельеф",
    ),
    tagSlugs: ["hitchhiking", "adventure", "low-budget"],
    relatedSlugs: ["theth-albanian-alps", "roads-villages-shared-tables", "demo-traveler-maksim"],
    source: editorialSource(
      "Veya safety oriented educational content. No ride or route availability is implied.",
      "Образовательный материал Veya о безопасности. Наличие поездки или маршрута не подразумевается.",
    ),
    action: detailAction("/travel-styles/hitchhiking-travel", "Explore hitchhiking", "Изучить автостоп"),
  },
  {
    slug: "small-group-travel",
    title: localized("Small group travel", "Путешествия в малой группе"),
    summary: localized(
      "Share a route with a compact group and clear expectations.",
      "Разделить маршрут с небольшой группой и ясными ожиданиями.",
    ),
    description: localized(
      "Small groups can combine social connection with more flexibility than a large organized tour.",
      "Малые группы могут сочетать общение с большей гибкостью, чем крупный организованный тур.",
    ),
    practicalNote: localized(
      "Agree on pace, budget, responsibilities and personal space before departure.",
      "До выезда согласуйте темп, бюджет, обязанности и личное пространство.",
    ),
    media: media(
      "/assets/community-hero.jpg",
      "Small travel group meeting in nature",
      "Небольшая группа путешественников встречается на природе",
    ),
    tagSlugs: ["small-group", "community", "adventure"],
    relatedSlugs: ["roads-villages-shared-tables", "week-of-healthy-rhythm", "demo-traveler-ana"],
    source: editorialSource(
      "Veya educational content for the first tester release.",
      "Образовательный материал Veya для первой тестовой версии.",
    ),
    action: detailAction("/travel-styles/small-group-travel", "Explore small group travel", "Изучить путешествия в малой группе"),
  },
] as const satisfies readonly TravelStyle[];

export const places = [
  {
    kind: "place",
    slug: "gjirokaster-stone-city",
    title: localized("Gjirokaster", "Гирокастра"),
    summary: localized(
      "A hillside city of stone lanes and layered local history in southern Albania.",
      "Город на склоне с каменными улицами и многослойной местной историей на юге Албании.",
    ),
    description: localized(
      "Veya presents Gjirokaster as an editorial starting point for cultural walks, regional stories and slower exploration of southern Albania.",
      "Veya представляет Гирокастру как редакционную отправную точку для культурных прогулок, региональных историй и неспешного исследования юга Албании.",
    ),
    location: localized("Gjirokaster, Albania", "Гирокастра, Албания"),
    coordinates: { latitude: 40.0758, longitude: 20.1389 },
    coordinateLabel: localized("Gjirokaster city center", "Центр Гирокастры"),
    countryCode: "AL",
    category: "historic-city",
    categoryLabel: localized("Historic city", "Исторический город"),
    comfort: "comfortable",
    comfortLabel: localized("Comfortable city base", "Комфортная городская база"),
    status: "published",
    statusLabel: localized("Editorial place", "Редакционное место"),
    media: media(
      "/assets/veya-world.png",
      "Illustrated Veya landscape representing Gjirokaster",
      "Иллюстрированный пейзаж Veya, представляющий Гирокастру",
    ),
    tagSlugs: ["albania", "culture", "walking", "editorial"],
    travelStyleSlugs: ["cultural-travel", "slow-travel"],
    relatedSlugs: ["roads-villages-shared-tables", "albania-story-walk-concept", "veya-editorial-team"],
    source: editorialSource(
      "Editorial place profile. It does not represent a booking, host agreement or live availability.",
      "Редакционный профиль места. Он не означает бронирование, договоренность с хозяином или актуальную доступность.",
    ),
    actions: [detailAction("/explore/gjirokaster-stone-city")],
    featured: true,
  },
  {
    kind: "place",
    slug: "theth-albanian-alps",
    title: localized("Theth", "Тети"),
    summary: localized(
      "A mountain village and trail base in the Albanian Alps.",
      "Горная деревня и база для маршрутов в Албанских Альпах.",
    ),
    description: localized(
      "Theth anchors Veya content about mountain travel, route preparation and respectful exploration of remote landscapes.",
      "Тети служит основой для материалов Veya о горных путешествиях, подготовке маршрутов и уважительном исследовании удаленных ландшафтов.",
    ),
    location: localized("Theth, Albania", "Тети, Албания"),
    coordinates: { latitude: 42.395, longitude: 19.774 },
    coordinateLabel: localized("Theth village", "Деревня Тети"),
    countryCode: "AL",
    category: "mountain-village",
    categoryLabel: localized("Mountain village", "Горная деревня"),
    comfort: "simple",
    comfortLabel: localized("Simple mountain base", "Простая горная база"),
    status: "published",
    statusLabel: localized("Editorial place", "Редакционное место"),
    media: media(
      "/assets/albania-coast-road.jpg",
      "Road leading toward Albanian mountain landscapes",
      "Дорога к албанским горным ландшафтам",
    ),
    tagSlugs: ["albania", "mountains", "nature", "adventure", "editorial"],
    travelStyleSlugs: ["nature-travel", "low-budget-travel", "hitchhiking-travel"],
    relatedSlugs: ["roads-villages-shared-tables", "theth-trail-companion-interest", "albania-local-creator-call"],
    source: editorialSource(
      "Editorial place profile. Trail, weather and transport conditions must be checked independently.",
      "Редакционный профиль места. Состояние троп, погоду и транспорт нужно проверять отдельно.",
    ),
    actions: [detailAction("/explore/theth-albanian-alps")],
    featured: true,
  },
  {
    kind: "place",
    slug: "berat-riverside-quarters",
    title: localized("Berat", "Берат"),
    summary: localized(
      "A riverside Albanian city suited to cultural walks and local food stories.",
      "Албанский город у реки, подходящий для культурных прогулок и историй о местной еде.",
    ),
    description: localized(
      "The editorial profile connects Berat with architecture, neighborhood walks and future conversations with local hosts.",
      "Редакционный профиль связывает Берат с архитектурой, прогулками по кварталам и будущими разговорами с местными хозяевами.",
    ),
    location: localized("Berat, Albania", "Берат, Албания"),
    coordinates: { latitude: 40.7058, longitude: 19.9522 },
    coordinateLabel: localized("Berat riverside center", "Центр Берата у реки"),
    countryCode: "AL",
    category: "historic-city",
    categoryLabel: localized("Historic city", "Исторический город"),
    comfort: "comfortable",
    comfortLabel: localized("Comfortable city base", "Комфортная городская база"),
    status: "published",
    statusLabel: localized("Editorial place", "Редакционное место"),
    media: media(
      "/assets/community-hero.jpg",
      "Community scene representing local encounters in Berat",
      "Сцена сообщества, представляющая местные встречи в Берате",
    ),
    tagSlugs: ["albania", "culture", "local-food", "walking", "editorial"],
    travelStyleSlugs: ["cultural-travel", "slow-travel", "community-travel"],
    relatedSlugs: ["roads-villages-shared-tables", "berat-local-table-host-call", "veya-editorial-team"],
    source: editorialSource(
      "Editorial place profile. No host or workshop is confirmed by this entry.",
      "Редакционный профиль места. Эта запись не подтверждает хозяина или мастерскую.",
    ),
    actions: [detailAction("/explore/berat-riverside-quarters")],
  },
  {
    kind: "place",
    slug: "himara-coast",
    title: localized("Himara coast", "Побережье Химары"),
    summary: localized(
      "A southern Albanian coastal base for slower days, villages and sea landscapes.",
      "База на южном побережье Албании для неспешных дней, деревень и морских пейзажей.",
    ),
    description: localized(
      "Veya uses Himara as an editorial anchor for coastal routes that connect nature, small places and flexible travel rhythm.",
      "Veya использует Химару как редакционную точку для прибрежных маршрутов, соединяющих природу, небольшие места и гибкий ритм путешествия.",
    ),
    location: localized("Himara, Albania", "Химара, Албания"),
    coordinates: { latitude: 40.1017, longitude: 19.7447 },
    coordinateLabel: localized("Himara coastal center", "Центр Химары у побережья"),
    countryCode: "AL",
    category: "coastal-town",
    categoryLabel: localized("Coastal town", "Прибрежный город"),
    comfort: "flexible",
    comfortLabel: localized("Flexible coastal base", "Гибкая база у моря"),
    status: "published",
    statusLabel: localized("Editorial place", "Редакционное место"),
    media: media(
      "/assets/albania-coast-road.jpg",
      "Albanian coast road near sea and mountains",
      "Албанская прибрежная дорога между морем и горами",
    ),
    tagSlugs: ["albania", "coast", "nature", "slow-pace", "editorial"],
    travelStyleSlugs: ["slow-travel", "nature-travel", "small-group-travel"],
    relatedSlugs: ["roads-villages-shared-tables", "coastal-slow-days-interest", "veya-editorial-team"],
    source: editorialSource(
      "Editorial place profile. Seasonal access and accommodation must be checked before travel.",
      "Редакционный профиль места. Сезонную доступность и жилье нужно проверять до поездки.",
    ),
    actions: [detailAction("/explore/himara-coast")],
    featured: true,
  },
  {
    kind: "place",
    slug: "lake-ohrid-shore",
    title: localized("Lake Ohrid shore", "Берег Охридского озера"),
    summary: localized(
      "A Balkans lake setting for cultural exploration, walking and a calmer rhythm.",
      "Озерное место на Балканах для культурного исследования, прогулок и спокойного ритма.",
    ),
    description: localized(
      "The Ohrid profile supports cross border Balkans discovery and early concepts combining nature, culture and wellbeing.",
      "Профиль Охрида поддерживает исследование Балкан и ранние концепты, объединяющие природу, культуру и благополучие.",
    ),
    location: localized("Ohrid, North Macedonia", "Охрид, Северная Македония"),
    coordinates: { latitude: 41.1172, longitude: 20.8016 },
    coordinateLabel: localized("Ohrid lakefront", "Набережная Охрида"),
    countryCode: "MK",
    category: "lake-city",
    categoryLabel: localized("Lake city", "Город у озера"),
    comfort: "comfortable",
    comfortLabel: localized("Comfortable lake base", "Комфортная база у озера"),
    status: "published",
    statusLabel: localized("Editorial place", "Редакционное место"),
    media: media(
      "/assets/veya-world.png",
      "Illustrated Veya landscape representing Lake Ohrid",
      "Иллюстрированный пейзаж Veya, представляющий Охридское озеро",
    ),
    tagSlugs: ["balkans", "north-macedonia", "nature", "culture", "editorial"],
    travelStyleSlugs: ["wellbeing-travel", "cultural-travel", "slow-travel"],
    relatedSlugs: ["week-of-healthy-rhythm", "balkans-wellbeing-place-call", "balkans-community-atlas"],
    source: editorialSource(
      "Editorial regional profile. It does not confirm a retreat, event or local partner.",
      "Редакционный региональный профиль. Он не подтверждает ретрит, событие или местного партнера.",
    ),
    actions: [detailAction("/explore/lake-ohrid-shore")],
  },
  {
    kind: "place",
    slug: "kotor-bay",
    title: localized("Kotor Bay", "Которский залив"),
    summary: localized(
      "A dramatic Montenegrin bay connecting historic towns, mountains and coastal routes.",
      "Выразительный залив в Черногории, соединяющий исторические города, горы и прибрежные маршруты.",
    ),
    description: localized(
      "Veya presents Kotor Bay as a regional discovery anchor for slower coastal travel and future work stay research.",
      "Veya представляет Которский залив как региональную точку для медленных прибрежных путешествий и будущего исследования формата проживания с работой.",
    ),
    location: localized("Kotor, Montenegro", "Котор, Черногория"),
    coordinates: { latitude: 42.4247, longitude: 18.7712 },
    coordinateLabel: localized("Kotor waterfront", "Набережная Котора"),
    countryCode: "ME",
    category: "coastal-bay",
    categoryLabel: localized("Coastal bay", "Прибрежный залив"),
    comfort: "comfortable",
    comfortLabel: localized("Comfortable regional base", "Комфортная региональная база"),
    status: "published",
    statusLabel: localized("Editorial place", "Редакционное место"),
    media: media(
      "/assets/veya-world.png",
      "Illustrated Veya route representing Kotor Bay",
      "Иллюстрированный маршрут Veya, представляющий Которский залив",
    ),
    tagSlugs: ["balkans", "montenegro", "coast", "culture", "editorial"],
    travelStyleSlugs: ["slow-travel", "remote-work-travel", "cultural-travel"],
    relatedSlugs: ["home-for-living-and-working", "mediterranean-work-stay-interest", "balkans-community-atlas"],
    source: editorialSource(
      "Editorial regional profile. It does not represent accommodation availability or a work stay offer.",
      "Редакционный региональный профиль. Он не означает доступность жилья или предложение проживания для работы.",
    ),
    actions: [detailAction("/explore/kotor-bay")],
  },
] as const satisfies readonly Place[];

export const journeys = [
  {
    kind: "journey",
    slug: "roads-villages-shared-tables",
    title: localized("Roads, villages and shared tables", "Дороги, деревни и общие столы"),
    summary: localized(
      "A relaxed concept route through southern Albania, nature and small family run places.",
      "Концепт спокойного маршрута через юг Албании, природу и небольшие семейные места.",
    ),
    description: localized(
      "This existing Veya journey concept links coastal and inland Albania without claiming confirmed hosts, dates or prices.",
      "Этот существующий концепт путешествия Veya соединяет побережье и внутренние районы Албании без заявлений о подтвержденных хозяевах, датах или ценах.",
    ),
    location: localized("Southern Albania", "Южная Албания"),
    coordinates: { latitude: 40.1017, longitude: 19.7447 },
    coordinateLabel: localized("Representative route anchor near Himara", "Ориентир маршрута рядом с Химарой"),
    status: "gathering-interest",
    statusLabel: localized("Gathering interest", "Собираем интерес"),
    duration: localized("7 to 9 days", "7-9 дней"),
    groupSize: localized("Concept for 6 to 10 people", "Концепт для 6-10 человек"),
    accommodation: localized("Homes and guesthouses, not confirmed", "Дома и гостевые места, не подтверждены"),
    pace: localized("Active without rushing", "Активно, без спешки"),
    availabilityNotice: localized(
      "Concept only. Dates, hosts, route and price remain unconfirmed.",
      "Только концепт. Даты, хозяева, маршрут и цена пока не подтверждены.",
    ),
    routePlaceSlugs: ["gjirokaster-stone-city", "berat-riverside-quarters", "himara-coast"],
    media: media(
      "/assets/albania-coast-road.jpg",
      "Road through the Albanian coast and mountains",
      "Дорога через албанское побережье и горы",
    ),
    tagSlugs: ["albania", "nature", "culture", "small-group", "concept"],
    travelStyleSlugs: ["slow-travel", "nature-travel", "small-group-travel"],
    relatedSlugs: ["gjirokaster-stone-city", "berat-riverside-quarters", "himara-coast", "albania-local-creator-call"],
    source: conceptSource(
      "Existing Veya journey concept carried forward from the original site. No live offer is implied.",
      "Существующий концепт путешествия Veya из исходного сайта. Актуальное предложение не подразумевается.",
    ),
    actions: [detailAction("/journeys/roads-villages-shared-tables"), interestAction("roads-villages-shared-tables")],
    featured: true,
  },
  {
    kind: "journey",
    slug: "week-of-healthy-rhythm",
    title: localized("A week of healthy rhythm", "Неделя здорового ритма"),
    summary: localized(
      "A Balkans wellbeing concept centered on food, walking, movement, rest and conversation.",
      "Балканский концепт благополучия с питанием, прогулками, движением, отдыхом и общением.",
    ),
    description: localized(
      "This journey concept explores supportive daily routines without medical promises and currently needs a suitable place partner.",
      "Этот концепт исследует поддерживающий повседневный ритм без медицинских обещаний и пока нуждается в подходящем месте-партнере.",
    ),
    location: localized("Balkans, place not selected", "Балканы, место не выбрано"),
    coordinates: { latitude: 41.1172, longitude: 20.8016 },
    coordinateLabel: localized("Editorial Balkans anchor near Ohrid", "Редакционный ориентир на Балканах рядом с Охридом"),
    status: "seeking-partner",
    statusLabel: localized("Seeking a place partner", "Ищем место-партнера"),
    duration: localized("Concept for 5 to 7 days", "Концепт на 5-7 дней"),
    groupSize: localized("Concept for 8 to 14 people", "Концепт для 8-14 человек"),
    accommodation: localized("Retreat style place, not confirmed", "Место ретритного формата, не подтверждено"),
    pace: localized("Calm and restorative", "Спокойный и восстанавливающий"),
    availabilityNotice: localized(
      "Concept only. No venue, dates, program or price is confirmed.",
      "Только концепт. Место, даты, программа и цена не подтверждены.",
    ),
    routePlaceSlugs: ["lake-ohrid-shore"],
    media: media(
      "/assets/community-hero.jpg",
      "Small group sharing a calm outdoor setting",
      "Небольшая группа в спокойной природной обстановке",
    ),
    tagSlugs: ["balkans", "wellbeing", "nature", "small-group", "concept"],
    travelStyleSlugs: ["wellbeing-travel", "slow-travel", "small-group-travel"],
    relatedSlugs: ["lake-ohrid-shore", "balkans-wellbeing-place-call", "balkans-community-atlas"],
    source: conceptSource(
      "Existing Veya journey concept carried forward from the original site. It is not a medical service.",
      "Существующий концепт путешествия Veya из исходного сайта. Это не медицинская услуга.",
    ),
    actions: [detailAction("/journeys/week-of-healthy-rhythm"), partnerAction("week-of-healthy-rhythm")],
    featured: true,
  },
  {
    kind: "journey",
    slug: "home-for-living-and-working",
    title: localized("A home for living and working", "Дом для жизни и работы"),
    summary: localized(
      "A longer Mediterranean stay concept for focused work, nature and a new social circle.",
      "Концепт долгого проживания в Средиземноморье для сосредоточенной работы, природы и нового круга общения.",
    ),
    description: localized(
      "The concept is still researching a region, a suitable house and reliable working conditions.",
      "Концепт пока исследует регион, подходящий дом и надежные условия для работы.",
    ),
    location: localized("Mediterranean, flexible region", "Средиземноморье, гибкий регион"),
    coordinates: { latitude: 42.4247, longitude: 18.7712 },
    coordinateLabel: localized("Editorial Mediterranean anchor near Kotor", "Редакционный ориентир в Средиземноморье рядом с Котором"),
    status: "concept",
    statusLabel: localized("Shaping the concept", "Формируем концепт"),
    duration: localized("Concept for 2 to 4 weeks", "Концепт на 2-4 недели"),
    groupSize: localized("Concept for 6 to 12 people", "Концепт для 6-12 человек"),
    accommodation: localized("House or community place, not confirmed", "Дом или место сообщества, не подтверждено"),
    pace: localized("Work focused with flexible exploration", "Фокус на работе с гибким исследованием"),
    availabilityNotice: localized(
      "Concept only. Internet, house, dates and shared budget are not confirmed.",
      "Только концепт. Интернет, дом, даты и общий бюджет не подтверждены.",
    ),
    routePlaceSlugs: ["kotor-bay", "himara-coast"],
    media: media(
      "/assets/veya-world.png",
      "Illustrated Veya home connected to travel routes",
      "Иллюстрированный дом Veya, соединенный с маршрутами",
    ),
    tagSlugs: ["mediterranean", "remote-work", "long-stay", "community", "concept"],
    travelStyleSlugs: ["remote-work-travel", "slow-travel", "community-travel"],
    relatedSlugs: ["kotor-bay", "himara-coast", "mediterranean-work-stay-interest", "balkans-community-atlas"],
    source: conceptSource(
      "Existing Veya journey concept carried forward from the original site. No stay is currently bookable.",
      "Существующий концепт путешествия Veya из исходного сайта. Сейчас проживание нельзя забронировать.",
    ),
    actions: [detailAction("/journeys/home-for-living-and-working"), interestAction("home-for-living-and-working")],
    featured: true,
  },
] as const satisfies readonly Journey[];

export const opportunities = [
  {
    kind: "opportunity",
    slug: "albania-story-walk-concept",
    title: localized("Albania story walk concept", "Концепт прогулки по историям Албании"),
    summary: localized(
      "A Veya idea for a guided cultural walk shaped with a future local contributor.",
      "Идея Veya для культурной прогулки, которую предстоит создать вместе с местным участником.",
    ),
    description: localized(
      "This is an editorial concept for testing interest. No guide, date, route or paid offer is confirmed.",
      "Это редакционный концепт для проверки интереса. Гид, дата, маршрут и платное предложение не подтверждены.",
    ),
    location: localized("Gjirokaster, Albania", "Гирокастра, Албания"),
    coordinates: { latitude: 40.0758, longitude: 20.1389 },
    coordinateLabel: localized("Concept anchor in Gjirokaster", "Ориентир концепта в Гирокастре"),
    status: "concept",
    statusLabel: localized("Veya concept", "Концепт Veya"),
    category: "experience",
    categoryLabel: localized("Experience concept", "Концепт опыта"),
    participationType: localized("Register interest in future co-creation", "Сообщить об интересе к будущему совместному созданию"),
    requirements: localized("No participant requirements because this is not yet an available activity", "Требований к участникам нет, потому что активность пока недоступна"),
    availability: {
      state: "concept",
      notice: localized("Not scheduled and not bookable", "Не запланировано и недоступно для бронирования"),
    },
    organiserSlug: "veya-editorial-team",
    media: media(
      "/assets/veya-world.png",
      "Illustrated streets for an Albania story walk concept",
      "Иллюстрированные улицы для концепта прогулки по историям Албании",
    ),
    tagSlugs: ["albania", "culture", "walking", "concept"],
    travelStyleSlugs: ["cultural-travel", "slow-travel"],
    relatedSlugs: ["gjirokaster-stone-city", "veya-editorial-team", "roads-villages-shared-tables"],
    source: conceptSource(
      "Veya owned concept created for product testing. It is not an external listing.",
      "Собственный концепт Veya для тестирования продукта. Это не внешнее объявление.",
    ),
    actions: [detailAction("/opportunities/albania-story-walk-concept"), interestAction("albania-story-walk-concept")],
  },
  {
    kind: "opportunity",
    slug: "theth-trail-companion-interest",
    title: localized("Theth trail companion interest", "Интерес к спутникам для маршрута в Тети"),
    summary: localized(
      "A Veya interest signal for people considering a prepared mountain journey in northern Albania.",
      "Сигнал интереса Veya для людей, рассматривающих подготовленное горное путешествие на севере Албании.",
    ),
    description: localized(
      "This entry tests demand for future small group exploration. It does not announce a departure or match travelers automatically.",
      "Эта запись проверяет интерес к будущему путешествию малой группой. Она не объявляет выезд и не подбирает спутников автоматически.",
    ),
    location: localized("Theth, Albania", "Тети, Албания"),
    coordinates: { latitude: 42.395, longitude: 19.774 },
    coordinateLabel: localized("Interest anchor in Theth", "Ориентир интереса в Тети"),
    status: "gathering-interest",
    statusLabel: localized("Gathering interest", "Собираем интерес"),
    category: "travel-group",
    categoryLabel: localized("Travel group concept", "Концепт группы путешественников"),
    participationType: localized("Share interest and preferred travel conditions", "Сообщить об интересе и предпочтительных условиях поездки"),
    requirements: localized("Future route preparation and safety review would be required", "В будущем потребуется подготовка маршрута и проверка безопасности"),
    availability: {
      state: "gathering-interest",
      notice: localized("No dates, group or route are confirmed", "Даты, группа и маршрут не подтверждены"),
    },
    organiserSlug: "veya-editorial-team",
    media: media(
      "/assets/albania-coast-road.jpg",
      "Mountain road representing a future Theth group concept",
      "Горная дорога, представляющая будущий групповой концепт в Тети",
    ),
    tagSlugs: ["albania", "mountains", "nature", "small-group", "concept"],
    travelStyleSlugs: ["nature-travel", "small-group-travel", "low-budget-travel"],
    relatedSlugs: ["theth-albanian-alps", "roads-villages-shared-tables", "albania-local-creator-call"],
    source: conceptSource(
      "Veya owned interest concept. It is not a live trip or an external traveler listing.",
      "Собственный концепт интереса Veya. Это не действующая поездка и не внешнее объявление путешественника.",
    ),
    actions: [detailAction("/opportunities/theth-trail-companion-interest"), interestAction("theth-trail-companion-interest")],
  },
  {
    kind: "opportunity",
    slug: "berat-local-table-host-call",
    title: localized("Berat local table host call", "Поиск хозяина местного стола в Берате"),
    summary: localized(
      "A Veya call to discuss a respectful local food and conversation concept in Berat.",
      "Поиск Veya для обсуждения уважительного концепта местной еды и общения в Берате.",
    ),
    description: localized(
      "Veya is looking for a potential contributor. No host, meal, event, payment or date is currently offered.",
      "Veya ищет возможного участника. Сейчас не предлагаются хозяин, трапеза, событие, оплата или дата.",
    ),
    location: localized("Berat, Albania", "Берат, Албания"),
    coordinates: { latitude: 40.7058, longitude: 19.9522 },
    coordinateLabel: localized("Partner call anchor in Berat", "Ориентир поиска партнера в Берате"),
    status: "partner-call",
    statusLabel: localized("Partner call", "Поиск партнера"),
    category: "community",
    categoryLabel: localized("Community partner call", "Поиск партнера сообщества"),
    participationType: localized("Introductory partner conversation", "Вводный разговор о партнерстве"),
    requirements: localized("Local context, transparent conditions and respect for participant consent", "Местный контекст, прозрачные условия и уважение к согласию участников"),
    availability: {
      state: "partner-call",
      notice: localized("No public experience is available", "Публичный опыт пока недоступен"),
    },
    organiserSlug: "veya-editorial-team",
    media: media(
      "/assets/community-table.png",
      "Community table representing a future local host conversation",
      "Общий стол, представляющий будущий разговор с местным хозяином",
    ),
    tagSlugs: ["albania", "local-food", "community", "partner-call"],
    travelStyleSlugs: ["community-travel", "cultural-travel", "slow-travel"],
    relatedSlugs: ["berat-riverside-quarters", "albania-local-creator-call", "balkans-community-atlas"],
    source: partnerCallSource(
      "Veya owned partner call. It must not be displayed as a confirmed host profile or available event.",
      "Собственный поиск партнера Veya. Его нельзя показывать как подтвержденный профиль хозяина или доступное событие.",
    ),
    actions: [detailAction("/opportunities/berat-local-table-host-call"), partnerAction("berat-local-table-host-call")],
  },
  {
    kind: "opportunity",
    slug: "balkans-wellbeing-place-call",
    title: localized("Balkans wellbeing place call", "Поиск места для программы благополучия на Балканах"),
    summary: localized(
      "A Veya search for a suitable place to shape a calm non-medical wellbeing journey concept.",
      "Поиск Veya подходящего места для спокойного немедицинского концепта путешествия для благополучия.",
    ),
    description: localized(
      "This call supports concept research only. There is no confirmed venue, program, treatment, date or price.",
      "Этот поиск нужен только для исследования концепта. Нет подтвержденного места, программы, лечения, даты или цены.",
    ),
    location: localized("Balkans, editorial anchor near Ohrid", "Балканы, редакционный ориентир рядом с Охридом"),
    coordinates: { latitude: 41.1172, longitude: 20.8016 },
    coordinateLabel: localized("Regional partner call anchor", "Региональный ориентир поиска партнера"),
    status: "partner-call",
    statusLabel: localized("Partner call", "Поиск партнера"),
    category: "retreat",
    categoryLabel: localized("Wellbeing place call", "Поиск места для благополучия"),
    participationType: localized("Discuss a possible venue collaboration", "Обсудить возможное сотрудничество с площадкой"),
    requirements: localized("Clear accommodation, food, accessibility and responsibility boundaries", "Ясные условия проживания, питания, доступности и границ ответственности"),
    availability: {
      state: "partner-call",
      notice: localized("No journey or wellbeing program is available", "Путешествие или программа благополучия пока недоступны"),
    },
    organiserSlug: "veya-editorial-team",
    media: media(
      "/assets/community-hero.jpg",
      "Calm outdoor setting representing a future wellbeing place",
      "Спокойная природная обстановка, представляющая будущее место для благополучия",
    ),
    tagSlugs: ["balkans", "wellbeing", "nature", "partner-call"],
    travelStyleSlugs: ["wellbeing-travel", "slow-travel"],
    relatedSlugs: ["lake-ohrid-shore", "week-of-healthy-rhythm", "veya-editorial-team"],
    source: partnerCallSource(
      "Veya owned partner call. It is not a medical, treatment or booking listing.",
      "Собственный поиск партнера Veya. Это не медицинское объявление, не лечение и не бронирование.",
    ),
    actions: [detailAction("/opportunities/balkans-wellbeing-place-call"), partnerAction("balkans-wellbeing-place-call")],
  },
  {
    kind: "opportunity",
    slug: "mediterranean-work-stay-interest",
    title: localized("Mediterranean work stay interest", "Интерес к проживанию с работой в Средиземноморье"),
    summary: localized(
      "A Veya interest concept for a focused longer stay with reliable working conditions.",
      "Концепт интереса Veya к долгому проживанию с надежными условиями для сосредоточенной работы.",
    ),
    description: localized(
      "The entry collects product interest only. No house, internet standard, dates, host or price is confirmed.",
      "Запись собирает только интерес к продукту. Дом, стандарт интернета, даты, хозяин и цена не подтверждены.",
    ),
    location: localized("Mediterranean, editorial anchor near Kotor", "Средиземноморье, редакционный ориентир рядом с Котором"),
    coordinates: { latitude: 42.4247, longitude: 18.7712 },
    coordinateLabel: localized("Work stay concept anchor near Kotor", "Ориентир концепта проживания с работой рядом с Котором"),
    status: "gathering-interest",
    statusLabel: localized("Gathering interest", "Собираем интерес"),
    category: "long-stay",
    categoryLabel: localized("Long stay concept", "Концепт долгого проживания"),
    participationType: localized("Share preferred dates, budget and work needs", "Сообщить предпочтительные даты, бюджет и рабочие потребности"),
    requirements: localized("No commitment until a place and all practical conditions are verified", "Никаких обязательств до проверки места и всех практических условий"),
    availability: {
      state: "gathering-interest",
      notice: localized("No stay is currently available", "Проживание пока недоступно"),
    },
    organiserSlug: "veya-editorial-team",
    media: media(
      "/assets/veya-world.png",
      "Illustrated home representing a future Mediterranean work stay",
      "Иллюстрированный дом, представляющий будущее проживание с работой в Средиземноморье",
    ),
    tagSlugs: ["mediterranean", "remote-work", "long-stay", "concept"],
    travelStyleSlugs: ["remote-work-travel", "slow-travel", "community-travel"],
    relatedSlugs: ["kotor-bay", "home-for-living-and-working", "balkans-community-atlas"],
    source: conceptSource(
      "Veya owned interest concept. It is not an accommodation or coworking listing.",
      "Собственный концепт интереса Veya. Это не объявление о жилье или коворкинге.",
    ),
    actions: [detailAction("/opportunities/mediterranean-work-stay-interest"), interestAction("mediterranean-work-stay-interest")],
  },
  {
    kind: "opportunity",
    slug: "coastal-slow-days-interest",
    title: localized("Coastal slow days interest", "Интерес к неспешным дням у моря"),
    summary: localized(
      "A Veya interest concept for slow coastal exploration around Himara.",
      "Концепт интереса Veya к неспешному исследованию побережья вокруг Химары.",
    ),
    description: localized(
      "This entry tests interest in a future coastal format. It does not confirm a host, activity, date or price.",
      "Эта запись проверяет интерес к будущему прибрежному формату. Она не подтверждает хозяина, активность, дату или цену.",
    ),
    location: localized("Himara, Albania", "Химара, Албания"),
    coordinates: { latitude: 40.1017, longitude: 19.7447 },
    coordinateLabel: localized("Interest anchor on the Himara coast", "Ориентир интереса на побережье Химары"),
    status: "gathering-interest",
    statusLabel: localized("Gathering interest", "Собираем интерес"),
    category: "travel-group",
    categoryLabel: localized("Slow travel group concept", "Концепт группы для неспешного путешествия"),
    participationType: localized("Share preferred rhythm and season", "Сообщить предпочтительный ритм и сезон"),
    requirements: localized("No commitment until the route and local conditions are verified", "Никаких обязательств до проверки маршрута и местных условий"),
    availability: {
      state: "gathering-interest",
      notice: localized("No coastal program is currently available", "Прибрежная программа пока недоступна"),
    },
    organiserSlug: "veya-editorial-team",
    media: media(
      "/assets/albania-coast-road.jpg",
      "Albanian coast road representing a future slow travel concept",
      "Албанская прибрежная дорога, представляющая будущий концепт неспешного путешествия",
    ),
    tagSlugs: ["albania", "coast", "slow-pace", "small-group", "concept"],
    travelStyleSlugs: ["slow-travel", "nature-travel", "small-group-travel"],
    relatedSlugs: ["himara-coast", "roads-villages-shared-tables", "demo-traveler-ana"],
    source: conceptSource(
      "Veya owned interest concept. It is not a live excursion or accommodation listing.",
      "Собственный концепт интереса Veya. Это не действующая экскурсия и не объявление о жилье.",
    ),
    actions: [detailAction("/opportunities/coastal-slow-days-interest"), interestAction("coastal-slow-days-interest")],
  },
] as const satisfies readonly Opportunity[];

export const creators = [
  {
    kind: "creator",
    slug: "veya-editorial-team",
    title: localized("Veya editorial team", "Редакционная команда Veya"),
    summary: localized(
      "The internal Veya role that researches, structures and clearly labels early discovery content.",
      "Внутренняя роль Veya, которая исследует, структурирует и ясно маркирует ранний контент для открытий.",
    ),
    description: localized(
      "This is a Veya owned editorial profile, not an independent guide or external travel agency.",
      "Это собственный редакционный профиль Veya, а не независимый гид или внешнее туристическое агентство.",
    ),
    location: localized("Albania and the Balkans", "Албания и Балканы"),
    coordinates: { latitude: 41.3275, longitude: 19.8187 },
    coordinateLabel: localized("Editorial regional anchor in Tirana", "Редакционный региональный ориентир в Тиране"),
    status: "published",
    statusLabel: localized("Veya editorial profile", "Редакционный профиль Veya"),
    profileMode: "editorial",
    languages: [localized("English", "Английский"), localized("Russian", "Русский")],
    specialties: [
      localized("Curated discovery", "Кураторский поиск"),
      localized("Journey concepts", "Концепты путешествий"),
      localized("Partner research", "Исследование партнеров"),
    ],
    profileNotice: localized(
      "Veya owned profile. It does not represent a local guide, host or confirmed operator.",
      "Собственный профиль Veya. Он не представляет местного гида, хозяина или подтвержденного оператора.",
    ),
    media: media(
      "/assets/veya-world.png",
      "Illustrated Veya world used for the editorial team",
      "Иллюстрированный мир Veya для редакционной команды",
    ),
    tagSlugs: ["albania", "balkans", "editorial"],
    travelStyleSlugs: ["slow-travel", "cultural-travel", "community-travel"],
    relatedSlugs: ["roads-villages-shared-tables", "week-of-healthy-rhythm", "home-for-living-and-working"],
    source: editorialSource(
      "Official Veya owned editorial profile for the MVP seed.",
      "Официальный собственный редакционный профиль Veya для начальных данных MVP.",
    ),
    actions: [detailAction("/guides-creators/veya-editorial-team", "View editorial profile", "Открыть редакционный профиль")],
    featured: true,
  },
  {
    kind: "creator",
    slug: "albania-local-creator-call",
    title: localized("Albania local creator call", "Поиск местных авторов в Албании"),
    summary: localized(
      "An open Veya invitation for guides, hosts and local storytellers to introduce their work.",
      "Открытое приглашение Veya для гидов, хозяев и местных рассказчиков представить свою работу.",
    ),
    description: localized(
      "This is a partner call profile, not a fictional creator and not an approved partner listing.",
      "Это профиль поиска партнеров, а не вымышленный автор и не объявление подтвержденного партнера.",
    ),
    location: localized("Albania", "Албания"),
    coordinates: { latitude: 40.0758, longitude: 20.1389 },
    coordinateLabel: localized("Regional call anchor in southern Albania", "Региональный ориентир поиска на юге Албании"),
    status: "partner-call",
    statusLabel: localized("Open partner call", "Открытый поиск партнеров"),
    profileMode: "partner-call",
    languages: [localized("Any language with clear communication", "Любой язык при ясной коммуникации")],
    specialties: [
      localized("Local knowledge", "Местные знания"),
      localized("Small scale experiences", "Небольшие локальные форматы"),
      localized("Responsible hosting", "Ответственный прием гостей"),
    ],
    profileNotice: localized(
      "No creator is represented by this page. Every future profile requires review and consent.",
      "Эта страница не представляет конкретного автора. Каждый будущий профиль требует проверки и согласия.",
    ),
    media: media(
      "/assets/community-table.png",
      "Community gathering representing an open local creator call",
      "Встреча сообщества, представляющая открытый поиск местных авторов",
    ),
    tagSlugs: ["albania", "community", "partner-call"],
    travelStyleSlugs: ["community-travel", "cultural-travel", "nature-travel"],
    relatedSlugs: ["gjirokaster-stone-city", "theth-albanian-alps", "berat-local-table-host-call"],
    source: partnerCallSource(
      "Veya owned invitation. It must remain visually distinct from approved creator profiles.",
      "Собственное приглашение Veya. Оно должно визуально отличаться от подтвержденных профилей авторов.",
    ),
    actions: [partnerAction("albania-local-creator-call")],
  },
] as const satisfies readonly Creator[];

export const projects = [
  {
    kind: "project",
    slug: "balkans-community-atlas",
    title: localized("Balkans community atlas", "Атлас балканских сообществ"),
    summary: localized(
      "A Veya editorial concept for mapping communities, projects and responsible ways to participate.",
      "Редакционный концепт Veya для карты сообществ, проектов и ответственных способов участия.",
    ),
    description: localized(
      "The atlas is an internal concept, not a claim that listed communities have joined Veya.",
      "Атлас является внутренним концептом и не означает, что перечисленные сообщества присоединились к Veya.",
    ),
    location: localized("Balkans, regional concept", "Балканы, региональный концепт"),
    coordinates: { latitude: 41.1172, longitude: 20.8016 },
    coordinateLabel: localized("Editorial regional anchor near Ohrid", "Редакционный региональный ориентир рядом с Охридом"),
    status: "concept",
    statusLabel: localized("Veya editorial concept", "Редакционный концепт Veya"),
    profileMode: "editorial",
    purpose: localized(
      "Make small community initiatives easier to discover without erasing their independent identity.",
      "Сделать небольшие инициативы сообществ заметнее, не стирая их самостоятельную идентичность.",
    ),
    participation: localized(
      "Future communities may review and approve their own public information before publication.",
      "В будущем сообщества смогут проверять и одобрять свою публичную информацию до публикации.",
    ),
    needs: [
      localized("Verified public information", "Проверенная публичная информация"),
      localized("Clear source attribution", "Ясное указание источников"),
      localized("Community consent", "Согласие сообщества"),
    ],
    profileNotice: localized(
      "No external community partnership is claimed by this concept profile.",
      "Этот концепт-профиль не заявляет о партнерстве с внешним сообществом.",
    ),
    media: media(
      "/assets/community-table.png",
      "Community table representing a future Balkans community atlas",
      "Общий стол, представляющий будущий атлас балканских сообществ",
    ),
    tagSlugs: ["balkans", "community", "learning", "concept"],
    travelStyleSlugs: ["community-travel", "volunteering-travel", "slow-travel"],
    relatedSlugs: ["lake-ohrid-shore", "kotor-bay", "berat-local-table-host-call"],
    source: conceptSource(
      "Veya owned editorial project concept. No external organisation is represented.",
      "Собственный редакционный концепт проекта Veya. Он не представляет внешнюю организацию.",
    ),
    actions: [detailAction("/projects/balkans-community-atlas", "View project concept", "Открыть концепт проекта")],
    featured: true,
  },
] as const satisfies readonly Project[];

export const people = [
  {
    kind: "person",
    slug: "demo-traveler-ana",
    title: localized("Demo traveler: Ana", "Демо-путешественник: Ана"),
    summary: localized(
      "Fictional profile exploring coastal nature, local culture and small groups.",
      "Вымышленный профиль с интересом к побережью, местной культуре и малым группам.",
    ),
    description: localized(
      "Ana exists only to demonstrate how public travel preferences and related discoveries may appear.",
      "Ана существует только для демонстрации публичных предпочтений и связанных открытий.",
    ),
    location: localized("Demo region: Central Europe", "Демо-регион: Центральная Европа"),
    status: "demo",
    statusLabel: localized("Demo profile", "Демо-профиль"),
    profileMode: "demo",
    languages: [localized("English", "Английский"), localized("Czech", "Чешский")],
    introduction: localized(
      "I enjoy slower coastal routes, shared meals and time to understand a place.",
      "Мне нравятся неспешные маршруты у моря, общие трапезы и время для понимания места.",
    ),
    preferredEnvironments: [localized("Coast", "Побережье"), localized("Historic towns", "Исторические города")],
    comfortLabel: localized("Flexible comfort", "Гибкий уровень комфорта"),
    travelRhythm: localized("Slow and moderately planned", "Медленно и умеренно спланировано"),
    socialStyle: localized("Small groups and local encounters", "Малые группы и встречи с местными"),
    currentDirection: localized("Demo direction: southern Albania", "Демо-направление: южная Албания"),
    socialLinks: [],
    media: media(
      "/assets/community-hero.jpg",
      "Abstract community image for fictional traveler Ana",
      "Абстрактное изображение сообщества для вымышленной путешественницы Аны",
    ),
    tagSlugs: ["demo-profile", "coast", "culture", "small-group"],
    travelStyleSlugs: ["slow-travel", "cultural-travel", "small-group-travel"],
    relatedSlugs: ["himara-coast", "roads-villages-shared-tables", "coastal-slow-days-interest"],
    source: demoSource(),
    actions: [detailAction("/people/demo-traveler-ana", "View demo profile", "Открыть демо-профиль")],
  },
  {
    kind: "person",
    slug: "demo-traveler-maksim",
    title: localized("Demo traveler: Maksim", "Демо-путешественник: Максим"),
    summary: localized(
      "Fictional profile interested in mountains, low budget routes and hitchhiking education.",
      "Вымышленный профиль с интересом к горам, бюджетным маршрутам и обучению автостопу.",
    ),
    description: localized(
      "Maksim is a demo identity for testing filters and compatibility, not a person available for contact.",
      "Максим является демо-профилем для тестирования фильтров и совместимости, а не человеком для связи.",
    ),
    location: localized("Demo region: Eastern Europe", "Демо-регион: Восточная Европа"),
    status: "demo",
    statusLabel: localized("Demo profile", "Демо-профиль"),
    profileMode: "demo",
    languages: [localized("Russian", "Русский"), localized("English", "Английский")],
    introduction: localized(
      "I prefer simple conditions, mountain routes and careful preparation with room for spontaneity.",
      "Я предпочитаю простые условия, горные маршруты и тщательную подготовку с местом для спонтанности.",
    ),
    preferredEnvironments: [localized("Mountains", "Горы"), localized("Remote nature", "Удаленная природа")],
    comfortLabel: localized("Simple and flexible", "Просто и гибко"),
    travelRhythm: localized("Flexible and active", "Гибко и активно"),
    socialStyle: localized("Independent or one companion", "Самостоятельно или с одним спутником"),
    currentDirection: localized("Demo direction: northern Albania", "Демо-направление: северная Албания"),
    socialLinks: [],
    media: media(
      "/assets/albania-coast-road.jpg",
      "Open road image for fictional traveler Maksim",
      "Изображение открытой дороги для вымышленного путешественника Максима",
    ),
    tagSlugs: ["demo-profile", "mountains", "adventure", "low-budget"],
    travelStyleSlugs: ["nature-travel", "low-budget-travel", "hitchhiking-travel"],
    relatedSlugs: ["theth-albanian-alps", "theth-trail-companion-interest", "roads-villages-shared-tables"],
    source: demoSource(),
    actions: [detailAction("/people/demo-traveler-maksim", "View demo profile", "Открыть демо-профиль")],
  },
  {
    kind: "person",
    slug: "demo-traveler-irina",
    title: localized("Demo traveler: Irina", "Демо-путешественник: Ирина"),
    summary: localized(
      "Fictional profile interested in calm lake settings, walking and everyday wellbeing.",
      "Вымышленный профиль с интересом к спокойным озерным местам, прогулкам и повседневному благополучию.",
    ),
    description: localized(
      "Irina demonstrates a non-medical wellbeing travel profile and has no real contact details.",
      "Ирина демонстрирует немедицинский профиль путешествия для благополучия и не имеет реальных контактных данных.",
    ),
    location: localized("Demo region: Baltic area", "Демо-регион: Балтийский регион"),
    status: "demo",
    statusLabel: localized("Demo profile", "Демо-профиль"),
    profileMode: "demo",
    languages: [localized("Russian", "Русский"), localized("English", "Английский")],
    introduction: localized(
      "I look for nature, comfortable routines, cultural walks and respectful small groups.",
      "Я ищу природу, комфортный ритм, культурные прогулки и уважительные малые группы.",
    ),
    preferredEnvironments: [localized("Lakes", "Озера"), localized("Walkable towns", "Города для прогулок")],
    comfortLabel: localized("Normal comfort", "Обычный комфорт"),
    travelRhythm: localized("Calm and planned", "Спокойно и спланировано"),
    socialStyle: localized("Small groups with personal space", "Малые группы с личным пространством"),
    currentDirection: localized("Demo direction: Lake Ohrid", "Демо-направление: Охридское озеро"),
    socialLinks: [],
    media: media(
      "/assets/community-hero.jpg",
      "Calm community image for fictional traveler Irina",
      "Спокойное изображение сообщества для вымышленной путешественницы Ирины",
    ),
    tagSlugs: ["demo-profile", "wellbeing", "walking", "small-group"],
    travelStyleSlugs: ["wellbeing-travel", "slow-travel", "small-group-travel"],
    relatedSlugs: ["lake-ohrid-shore", "week-of-healthy-rhythm", "balkans-wellbeing-place-call"],
    source: demoSource(),
    actions: [detailAction("/people/demo-traveler-irina", "View demo profile", "Открыть демо-профиль")],
  },
  {
    kind: "person",
    slug: "demo-traveler-luka",
    title: localized("Demo traveler: Luka", "Демо-путешественник: Лука"),
    summary: localized(
      "Fictional profile combining remote work, long stays and regional culture.",
      "Вымышленный профиль, соединяющий удаленную работу, долгое проживание и региональную культуру.",
    ),
    description: localized(
      "Luka is a demo identity used to test work stay discovery without implying a real user or available home.",
      "Лука является демо-профилем для тестирования поиска проживания с работой без намека на реального пользователя или доступный дом.",
    ),
    location: localized("Demo region: Southeast Europe", "Демо-регион: Юго-Восточная Европа"),
    status: "demo",
    statusLabel: localized("Demo profile", "Демо-профиль"),
    profileMode: "demo",
    languages: [localized("English", "Английский"), localized("Serbian", "Сербский")],
    introduction: localized(
      "I need reliable work conditions and enjoy staying long enough to join local routines.",
      "Мне нужны надежные условия для работы, и я люблю оставаться достаточно долго, чтобы войти в местный ритм.",
    ),
    preferredEnvironments: [localized("Coastal towns", "Прибрежные города"), localized("Nature near a city", "Природа рядом с городом")],
    comfortLabel: localized("Comfortable and practical", "Комфортно и практично"),
    travelRhythm: localized("Long stay with planned workdays", "Долгое проживание с запланированными рабочими днями"),
    socialStyle: localized("Independent with occasional community time", "Самостоятельно с периодическим участием в сообществе"),
    currentDirection: localized("Demo direction: Montenegro", "Демо-направление: Черногория"),
    socialLinks: [],
    media: media(
      "/assets/veya-world.png",
      "Illustrated Veya world for fictional traveler Luka",
      "Иллюстрированный мир Veya для вымышленного путешественника Луки",
    ),
    tagSlugs: ["demo-profile", "remote-work", "long-stay", "culture"],
    travelStyleSlugs: ["remote-work-travel", "slow-travel", "cultural-travel"],
    relatedSlugs: ["kotor-bay", "home-for-living-and-working", "mediterranean-work-stay-interest"],
    source: demoSource(),
    actions: [detailAction("/people/demo-traveler-luka", "View demo profile", "Открыть демо-профиль")],
  },
] as const satisfies readonly Person[];

export const discoverables: readonly Discoverable[] = [
  ...places,
  ...journeys,
  ...opportunities,
  ...creators,
  ...projects,
  ...people,
];

export const seedContent: MvpSeedContent = {
  filterTags,
  travelStyles,
  discoverables,
};

export const discoverableBySlug = new Map(
  discoverables.map((item) => [item.slug, item] as const),
);

export const travelStyleBySlug = new Map(
  travelStyles.map((style) => [style.slug, style] as const),
);
